# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user42/Documents/ft_ping

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user42/Documents/ft_ping

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user42/Documents/ft_ping/CMakeFiles /home/user42/Documents/ft_ping/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user42/Documents/ft_ping/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_ping

# Build rule for target.
ft_ping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft_ping
.PHONY : ft_ping

# fast build rule for target.
ft_ping/fast:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/build
.PHONY : ft_ping/fast

src/arguments_processing.o: src/arguments_processing.c.o

.PHONY : src/arguments_processing.o

# target to build an object file
src/arguments_processing.c.o:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/arguments_processing.c.o
.PHONY : src/arguments_processing.c.o

src/arguments_processing.i: src/arguments_processing.c.i

.PHONY : src/arguments_processing.i

# target to preprocess a source file
src/arguments_processing.c.i:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/arguments_processing.c.i
.PHONY : src/arguments_processing.c.i

src/arguments_processing.s: src/arguments_processing.c.s

.PHONY : src/arguments_processing.s

# target to generate assembly for a file
src/arguments_processing.c.s:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/arguments_processing.c.s
.PHONY : src/arguments_processing.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/main.c.s
.PHONY : src/main.c.s

src/network_part.o: src/network_part.c.o

.PHONY : src/network_part.o

# target to build an object file
src/network_part.c.o:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/network_part.c.o
.PHONY : src/network_part.c.o

src/network_part.i: src/network_part.c.i

.PHONY : src/network_part.i

# target to preprocess a source file
src/network_part.c.i:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/network_part.c.i
.PHONY : src/network_part.c.i

src/network_part.s: src/network_part.c.s

.PHONY : src/network_part.s

# target to generate assembly for a file
src/network_part.c.s:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/network_part.c.s
.PHONY : src/network_part.c.s

src/str_manip.o: src/str_manip.c.o

.PHONY : src/str_manip.o

# target to build an object file
src/str_manip.c.o:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/str_manip.c.o
.PHONY : src/str_manip.c.o

src/str_manip.i: src/str_manip.c.i

.PHONY : src/str_manip.i

# target to preprocess a source file
src/str_manip.c.i:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/str_manip.c.i
.PHONY : src/str_manip.c.i

src/str_manip.s: src/str_manip.c.s

.PHONY : src/str_manip.s

# target to generate assembly for a file
src/str_manip.c.s:
	$(MAKE) -f CMakeFiles/ft_ping.dir/build.make CMakeFiles/ft_ping.dir/src/str_manip.c.s
.PHONY : src/str_manip.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ft_ping"
	@echo "... edit_cache"
	@echo "... src/arguments_processing.o"
	@echo "... src/arguments_processing.i"
	@echo "... src/arguments_processing.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network_part.o"
	@echo "... src/network_part.i"
	@echo "... src/network_part.s"
	@echo "... src/str_manip.o"
	@echo "... src/str_manip.i"
	@echo "... src/str_manip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

